### ISSUE TITLE
ask for some help

### ISSUE THREAD

**Issue by raven3005672** [mohakpatel/Poisson-Disc-Sampling#2]
hello~
i'm a beginner about image processing. recent study the poisson sampling. i test your excellent code.
but i have a question about the input. if i have some 3d data, i want to use the code to sample the data.
how can i achieve the goal?

look forward to your reply~ thank you~

**Comment by mohakpatel** [comment]
Here is how you can sample 3D data

```matlab
sizeI = [512,512,192];  
spacing = 6;  
nPts = 10000;  
pts = poissonDisc(sizeI,spacing,nPts);  
```
