### ISSUE TITLE
3D Error

### ISSUE THREAD

**Issue by riss21** [mohakpatel/Poisson-Disc-Sampling#3]
Hello, I tried using your code in Matlab for 3D sampling but the error shown below was given.

Index in position 2 exceeds array bounds.

Error in poissonDisc (line 106)
    D = D(:,2);

Please help

**Comment by mohakpatel** [comment]
Hi riss21, 
Can you show me your call to the function so that I can replicate the issue? 

Thanks!

**Comment by riss21** [comment]
Hi Mohak,

Thank you for the reply.
I actually tried the example given and the error occurred.

sizeI = [512,512,192];

spacing = 6;

nPts = 10000;

pts = poissonDisc(sizeI,nPts,spacing);

Index in position 2 exceeds array bounds (must not exceed 1).


Error in poissonDisc (line 106)

    D = D(:,2);


Again, thank you!


Regards,

Riss

**Comment by mohakpatel** [comment]
Hi Riss, 
You have `nPts` and `spacing` in the wrong order in the call to the function. 

The correct call to the function is:
`pts = poissonDisc(sizeI,spacing,nPts);  `

Hope this helps!

**Comment by riss21** [comment]
Hi Mohak,

I did not notice that sorry.
Thank you very much.

😀

**Comment by mohakpatel** [comment]
No worries! Good luck using it :)
